config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :businesses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :type
  validates :name, :phone, :website, :address, :hours, :presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new
  end

  def create
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new(business_params)
    if @business.save
      redirect_to type_path(@business.type)
    else
      render :new
    end
  end

  def edit
    @type = Type.find(params[:type_id])
    @business = Business.find(params[:id])
    render :edit
  end

  def update
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to type_path(@business.type)
    else
      render :edit
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
  redirect_to type_path(@business.type)
  end

  def show
    @business = Business.find(params[:id])
    render :show
  end
  
  private
  def business_params
    params.require(:business).permit(:name, :phone, :address, :website, :hours)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end

  def new
    @type = Type.new
    render :new
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :new
    end
  end

  def edit
    @type = Type.find(params[:id])
    render :edit
  end

  def update
    @type = Type.find(params[:id])
    if @type.update(type_params)
      redirect_to types_path
    else
      render :edit
    end
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    redirect_to types_path
  end

  private
  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render('layouts/errors', :object => @business) %>

<%= form_for [@type, @business] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <p><%= f.submit %></p>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>

<%= render 'form' %>

app/views/businesses/new.html.erb
<h1>Add a business to <%= @type.name %> </h1>

<%= render 'form' %>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>
<hr>
<ul>
  <li>phone number: <%= @business.phone %></li>
  <li>address : <%= @business.address %></li>
  <li>website : <%= @business.website %></li>
  <li>hours : <%= @business.hours %></li>
</ul>

<p>
  <%= link_to @business.type.name, type_path(@business.type) %>
</p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikipages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= render "layouts/errors", :object => @type %>

<%= form_for @type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/types/edit.html.erb
<h1>Edit type</h1>

<%= render "form" %>

app/views/types/index.html.erb
<h1>Business types</h1>

<ul>
  <% @types.each do |type| %>
    <li> <%= link_to type.name, type_path(type) %> </li>
  <% end %>
</ul>

<hr>

<%= link_to "New business type", new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render "form" %>

app/views/types/show.html.erb
<h1> <%= @type.name %> </h1>

<% if @type.businesses.any? %>
  <h4>Here are the businesses for <%= @type.name %>: </h4>

  <ul>
    <% @type.businesses.each do |business| %>
      <li>
        <%= link_to business.name, type_business_path(@type, business) %>
        <%= link_to "edit", edit_type_business_path(@type, business) %> |
        <%= link_to "delete", type_business_path(@type, business),
                                  :data => {:confirm => "Are you sure?",
                                              :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no businesses yet</p>
<% end %>

<p> <%= link_to "Add a business", new_type_business_path(@type) %></p>
<p><%= link_to "edit", edit_type_path(@type) %></p>
<p><%= link_to "delete", type_path(@type),
                         :data => {:confirm => "You sure?",
                         :method => "delete"} %></p>

<p><%= link_to "Return to types page", types_path %></p>